name: nomnom
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  go_router: ^7.0.1
  firebase_core: ^2.12.0
  google_fonts: ^4.0.4
  firebase_auth: ^4.6.0
  dio: ^5.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  envied: ^0.3.0+3
  logger_flutter_fork: ^1.3.1
  logger_fork: ^1.2.0
  flutter_svg: ^2.0.6
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  fraction: ^5.0.0
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5
  image_picker: ^1.0.1
  flutter_firebase_chat_core: ^1.6.7
  flutter_chat_types: ^3.6.2
  flutter_image_compress: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  build_runner: ^2.4.2
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/avatars/
    - assets/challenges/
    - assets/icons/
    - assets/onboarding/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
