// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '1:172376583617:web:b3ab016f7e43950e1c5340',
    appId: '1:708737726793:web:aab7601652171bb49fc298',
    messagingSenderId: '172376583617',
    projectId: 'nomnom2-41443',
    authDomain: 'nomnom2-41443.firebaseapp.com',
    storageBucket: 'nomnom2-41443.appspot.com',
    measurementId: "G-4N5R64H1R0"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo8LsvjNgz8rQAk3qzz6zi0RSHStZYWvA',
    appId: '1:172376583617:android:1ac1293b832cd7aa1c5340',
    messagingSenderId: '172376583617',
    projectId: 'nomnom2-41443',
    storageBucket: 'nomnom2-41443.appspot.com',
  );
}
